Repository UniversalMediaServer/UniversalMediaServer, pull requests merged in 2018-11, with the labels that each got.

#1625 Removed dependency on plexus StringUtils
  pom.xml
  src/main/java/net/pms/dlna/virtual/VirtualFolder.java
  src/main/java/net/pms/util/FileUtil.java
  src/main/java/net/pms/util/OpenSubtitle.java
  src/main/java/net/pms/util/TempFileMgr.java
Labels: awaiting review

#1609 Update Cling and Seamless to resolve security issue
  pom.xml
Labels: awaiting testing

#1657 Handling the "Album Artist" field present in the audio files.
  src/main/java/net/pms/dlna/DLNAMediaAudio.java
  src/main/java/net/pms/dlna/DLNAMediaDatabase.java
  src/main/java/net/pms/dlna/DLNAResource.java
  src/main/java/net/pms/dlna/LibMediaInfoParser.java
  src/main/java/net/pms/dlna/virtual/MediaLibrary.java
  src/main/java/net/pms/util/UMSUtils.java
Labels: enhancement
